services:
  we-talk-api:
    container_name: wetalk.api
    image: jicoy0120/dotnet-img:1.0.0
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_URLS=http://+:80  # Bind to all network interfaces
      - ASPNETCORE_ENVIRONMENT=Production
      # - ConnectionStrings__MainDB=server=mysql;database=wetalk;uid=wetalk_web;pwd=FdO42-ddI4_G4r
      # - ConnectionStrings__MainDB=server=097e76a00d8b4cc98bd4f8e009a3c1bbin01.internal.ap-southeast-1.mysql.rds.myhuaweicloud.com;database=wetalk;uid=root;pwd=p@w3rFUlLt3am@dm!nITiDep
      - ConnectionStrings__MainDB=server=192.168.0.186:3306;database=wetalk;uid=root;pwd=p@w3rFUlLt3am@dm!nITiDep
    networks:
      - app-network
    depends_on:
      - redis
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wetalk.phpmyadmin
    environment:
      - PMA_HOST=192.168.0.186  # Huawei RDS endpoint thru private ip
      # - PMA_HOST=159.138.55.8  # Huawei RDS endpoint thru eip
      - PMA_USER=root           # RDS user
      - PMA_PASSWORD=p@w3rFUlLt3am@dm!nITiDep  # RDS password
      - PMA_PORT=3306           # Default MySQL port
      # - PMA_HOSTS=159.138.55.8  # Ensure connection to your MySQL instance thru eip
      - PMA_HOSTS=192.168.0.186  # Ensure connection to your MySQL instance thru private ip
      
      # p@w3rFUlLt3am@dm!nITiDep rds password
      # wt_p43wrFUlLt3AM@Dm!n ecs password
    ports:
      - "8080:80"
    depends_on:
      - we-talk-api
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: wetalk.redis
    command: redis-server --requirepass Ue2l8ke36922888
    ports:
      - "6379:6379"
    volumes:
      - ./docker-volumes/redis:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge